### ISSUE TITLE
Send reminder for creating wishlist

### ISSUE THREAD

**Issue by Lydienne75** [iodigital-com/SecretSanta#558]
Would be really cool to have the possibility to send a reminder to everyone on the list who has not entered their wishlist yet.

**Comment by RubenHollevoet** [comment]
I get the idea but personally don't think there is enough added value to introduce a new type of email.
I don't think al lot of people would be using it since not all parties make use of the wishlist, a user can already send anonymous messages to his buddy if he is in need for some hints and probably almost all groups would have private chats or other means of communication next to the platform to ask those general questions.

Besides that, we would also need to gather the copy in all languages available on the platform for the extra copy.
