### ISSUE TITLE
Validation email not received

### ISSUE THREAD

**Issue by WillDaSilva** [iodigital-com/SecretSanta#590]
I set up a list, and proceeded to the page that says:

> Only 1 step to go! - Validate your participation

No email has been received at the address provided after waiting 15 minutes. I've checked my spam filter. I'm using a typical `gmail.com` address. I've double checked that the email address can receive emails by copying it from the "validate your participation" page, and sending it an email from a different account.

I think the email service used by https://www.secretsantaorganizer.com/ may not be working.

**Comment by TomCan** [comment]
Hi Will

Due to the large amount of parties starting up, we're experiencing delays in getting all e-mails out of the door specifically on @gmail.com addresses. They are being delivered, but Google appears to be actively throttling us. E-mails to other domains are going through near instantly, so I'm affraid is just a matter of waiting.
