### ISSUE TITLE
Simplify it by not requiring to press any buton in the email, ability to replace text

### ISSUE THREAD

**Issue by darius-v** [iodigital-com/SecretSanta#592]
There is lithuanian site kamdovanoti.lt but it stopped sending emails due to big load and no income. So I found your site.
But I see it is bit more complex, especially for people not knowing english.

kamdovanoti.lt sends simple email
![image](https://github.com/user-attachments/assets/253f9099-c2dc-4ebf-9bf0-a058a039ee05)

and there is list of emails and names below in the email but I dit not add for privact. But basically you do not need to press anything, you got your text and see who you have to give gift.

Now people who do not underst english might be overwhelmed with information. Could be just an option to enter your own text to replace the english text.

Btw also there is in our case 2 people with same name and surnames, so host might not notice that email and not add some identifier to the name, email is not shown so once someone receives info to whom to give gift - in that case he might not know whom of those 2 people give gift. Of course this is real edge case but it exists :D

**Comment by tvlooy** [comment]
We want to expose the match on the website so we want to keep the button. When you create a party in a certain language we support on the site, the email should also be in that language. That is something we need to check.

About the duplicate names, yeah you will have to add something to their name to indicate who is who I guess.

**Comment by TomCan** [comment]
There are multiple reasons why we opted for the e-mail + click process we have know.

1. You keep the secrecy to a maximum.
2. It helps an organizer keep track of who has actually opened/viewed their match.
3. The site offers tools like a wishlist and the ability to anonymous contact your match. 

Other than the party comment, we do not allow to put in any custom text. The problem is that sending out e-mails with user-generated content is prone to spam abuse. We've had problems like that in the past, so we really need to be carefull. A few bad actors are enough to ruin our e-mail repuration and cause delivery issues for all of our users.

As for the language barrier. Unfortunately we don't speak every language. With the help of the community, we are able to offer 9 different languages. Adding new languages is possible, with it requires that someone native translates the entire site into that language, and that's quite the task. Also, as we are adding new features that often include new text, those also need to be translated into all available languages.

**Comment by tvlooy** [comment]
I just checked. When you create a party in Spanish, your activation mail is in Spanish. When you start the party those mails are also in Spanish. At least this is how we want it to be.
